server:
  port: 8035
  error:
    include-stacktrace: always

spring:
  application:
    name: ecommerce-anyuruf
  profiles:
    active: default
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email,profile,offline
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    
datastax:
  astra:
    secure-connect-bundle: ${ASTRA_BUNDLE:${user.home}/.astra/secure-connect-demo.zip}
      
logging:
  level:
    '[org.springframework.security]': DEBUG

